# Generated by Django 3.1.1 on 2020-09-30 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicTacToe', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='score_player1',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='score_player2',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('0', 'Game Over'), ('1', 'In Progress')], default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='room',
            name='total_matches',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
