# Generated by Django 3.1.1 on 2020-09-30 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicTacToe', '0002_auto_20200930_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='total_matches',
            field=models.IntegerField(blank=True, default=5, null=True),
        ),
    ]
