# Generated by Django 3.1.1 on 2020-10-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TicTacToe', '0003_auto_20200930_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='winner',
            field=models.CharField(max_length=1000, null=True, unique=True),
        ),
    ]
